    firstName, middleName, lastName, gender, age,

    address,
    city,
    province,
    postal,
    country,
    mobilePhone,

    homePhone: "",
    workPhone: "",
    emergencyContactName: "",
    emergencyContactNumber: "",
    email: "",
    firstLanguage: "",
    aboutUs: "",

    childProgram: "",
    afterSchoolProgram: "",
    healthZumba: "",
    healthYoga: "",
    healthDental: "",
    healthKarate: "",
    healthMeditation: "",
    healthFoodMarket: "",
    
    healthBellyDancing: "",
    healthAdultPlus: "",
    healthEnglishCafe: "",
    healthBasicEnglish: "",
    healthHomeVistits: "",
    healthSocialGroup: "",
    healthHealthySmiles: "",
    healthVolleyBall: "",
    healthHeartAndStroke: "",
    healthFoodShareBus: "",
    healthDieticianSessions: "",
    healthFoodHandling: "",
    healthAdultNutrition: "",
    healthDiabetesSessions: "",
    healthHealthyChoices: "",
    healthHomeManagement: "",
    healthStressManagement: "",
    healthCancerScreeningSpa: "",
    healthDiabetesManagement: "",
    healthSwimmingChildren: "",
    healthSwimmingLadies: "",
    healthSwimmingAquaFitMale: "",
    healthSwimmingAquaFitFemale: "",
    healthTutoring: "",
    jobClub: "",
    childMinding: "",
    computerBasic: "",
    citizenshipRefugees: "",
    communityAssistant: "",
    computerIntermediate: "",
    interestedInVolunteering: "",
    publicSpeaking: "",
    foreignTrainedHealthProfessionals: "",
    staff: "",
    neighbourhoodNet: "",
    neighbourhoodIncomeTax: "",
    neighbourhoodOther: "",
    othersTextArea: "",
    agentNotesTextArea: "",
    memberHealth: "",
    memberSatisfaction: "",
    memberSocialNetwork: "",
    memberConnection: "",
    memberStress: "",
    memberPersonalHealth: "",
    memberFamilyDoctor: "",
    memberFamilyVisitFamilyDoctor: "",
    memberFamilyVisitClinic: "",
    memberFamilyVisitEmergencyRoom: "",
    memberFamilyVisitHospital: "",
    memberRiskFactors: "",
    memberFamilyhealthyLiving: "",
    memberFamilyPhysicallyActive: ""